### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by marijagjorgjieva** [marijagjorgjieva/SushiCat#1]
Game Menu
![GameMenu](https://user-images.githubusercontent.com/82838042/177001691-b42fe4d0-8dd1-475c-912e-faf73bbee636.jpg)

How to play
![HowToPlay](https://user-images.githubusercontent.com/82838042/177001722-5cef050c-2507-4578-b839-03a3f5427ce9.jpg)

Customize screen
![CustomizeScreen](https://user-images.githubusercontent.com/82838042/177001735-0b2e4aaf-ebd3-4906-90cf-aa6ce2235bc8.jpg)

Gameplay
![Gameplay](https://user-images.githubusercontent.com/82838042/177001744-058340d0-d9d7-4834-a157-e25e77b453f4.jpg)

Win Screen
![WinScreen](https://user-images.githubusercontent.com/82838042/177001761-5b7155d9-2301-4b4b-a294-eb460e9b22a6.jpg)

**Comment by andrejdaskalov** [comment]
What are the steps to reproduce your issue?
